"""
Django settings for NewsPortal project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-xr_(z(b#$6qp(km38tq3_xgd*17fxj_o)&wa=k9s(=&al3r!l7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]


INSTALLED_APPS = [
    'modeltranslation', # обязательно впишите его перед админом
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.flatpages',
    'news_portal',
    'accounts',
    'django_filters',
    'django_apscheduler',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.yandex',
    'rest_framework',
]


SITE_ID = 1



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.middleware.locale.LocaleMiddleware',

    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'django.contrib.flatpages.middleware.FlatpageFallbackMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'news_portal.middlewares.TimezoneMiddleware', # add that middleware!
]

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale')
]

SOCIALACCOUNT_PROVIDERS = {
    'yandex': {
        # For each OAuth based provider, either add a ``SocialApp``
        # (``socialaccount`` app) containing the required client
        # credentials, or list them here:
        'APP': {
            'client_id': '123',
            'secret': '456',
            'key': ''
        }
    }
}

ROOT_URLCONF = 'NewsPortal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.request',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# AUTHENTICATION_BACKENDS = [
#     'django.contrib.auth.backends.ModelBackend',
#     'allauth.account.auth_backends.AuthenticationBackend',
# ]

WSGI_APPLICATION = 'NewsPortal.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

LANGUAGE = [
    ('ru', 'Русский'),
    ('en-us', 'Englich'),
]

TIME_ZONE = 'UTC'

USE_i18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


STATICFILES_DIRS = [
    BASE_DIR / "static"
]

LOGIN_REDIRECT_URL = "/news"

SITE_URL = 'http://127.0.0.1:8000'


ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_FORMS = {"signup": "accounts.forms.CustomSignupForm"}


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.yandex.ru'
EMAIL_PORT = 465
EMAIL_HOST_USER = "example@yandex.ru"
EMAIL_HOST_PASSWORD = "iliezvcovrxqizez"
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True

DEFAULT_FROM_EMAIL = "example@yandex.ru"

SERVER_EMAIL = "example@yandex.ru"
MANAGERS = (
    ('Ivan', 'ivan@yandex.ru'),
    ('Petr', 'petr@yandex.ru'),
)

APSCHEDULER_DATETIME_FORMAT = 'N j, Y, f:s a'

APSCHEDULER_RUN_NOW_TIMEOUT = 25


CELERY_BROKER_URL = 'redis://localhost:6379'
CELERY_RESULT_BACKEND = 'redis://localhost:6379'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'


CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': os.path.join(BASE_DIR, 'cache_files'),
        'TIMEOUT': 30,
    }
}


# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'style': '{',
#     'formatters': {
#         'simple': {
#             'format': '%(asctime)s %(levelname)s %(message)s',
#             'datefmt': '%d/%m/%Y %H:%M:%S'
#         },
#         'console_warning' :{
#             'format': '%(asctime)s %(levelname)s %(message)s %(pathname)s',
#             'datefmt': '%d.%m.%Y %H-%M-%S',
#         },
#         'console_error': {
#             'format': '%(asctime)s %(levelname)s %(message)s %(pathname)s %(exc_info)',
#             'datefmt': '%d.%m.%Y %H-%M-%S',
#         },
#         'console_error_critical': {
#             'format': '%(asctime)s %(levelname)s %(message)s %(pathname)s %(exc_info)',
#             'datefmt': '%d.%m.%Y %H-%M-%S',
#         },
#         'general': {
#             'format': '%(asctime)s %(levelname)s %(module)s %(message)s',
#             'datefmt': '%d.%m.%Y %H-%M-%S',
#         },
#         'errors': {
#             'format': '%(asctime)s %(levelname)s %(message)s %(pathname)s %(exc_info)',
#             'datefmt': '%d.%m.%Y %H-%M-%S',
#         },
#         'security': {
#             'format': '%(asctime)s %(levelname)s %(module)s %(message)s',
#             'datefmt': '%d.%m.%Y %H-%M-%S',
#         },
#         'mail': {
#             'format': '%(asctime)s %(levelname)s %(message)s %(pathname)s',
#             'datefmt': '%d.%m.%Y %H-%M-%S',
#         }
#     },
#     'filters': {
#         'require_debug_true': {
#             '()': 'django.utils.log.RequireDebugTrue',
#         },
#         'require_debug_false': {
#             '()': 'django.utils.log.RequireDebugFalse',
#         },
#     },
#     'handlers': {
#         'console': {
#             'level': 'INFO',
#             'filters': ['require_debug_true'],
#             'class': 'logging.StreamHandler',
#             'formatter': 'simple',
#         },
#     'console_warning': {
#             'level': 'WARNING',
#             'filters': ['require_debug_true'],
#             'class': 'logging.StreamHandler',
#             'formatter': 'console_warning'
#         },
#     'console_error': {
#             'level': 'ERROR',
#             'filters': ['require_debug_true', ],
#             'class': 'logging.StreamHandler',
#             'formatter': 'console_error_critical'
#         },
#     'console_critical': {
#             'level': 'CRITICAL',
#             'filters': ['require_debug_true', ],
#             'class': 'logging.StreamHandler',
#             'formatter': 'console_error_critical'
#         },
#     'general_info': {
#             'level': 'INFO',
#             'filters': ['require_debug_false', ],
#             'class': 'logging.FileHandler',
#             'filename': 'logs/general.log',
#             'formatter': 'general',
#         },
#     'errors_error': {
#             'level': 'ERROR',
#             'class': 'logging.FileHandler',
#             'filename': 'logs/errors.log',
#             'formatter': 'errors',
#         },
#     'errors_critical': {
#             'level': 'CRITICAL',
#             'class': 'logging.FileHandler',
#             'filename': 'logs/errors.log',
#             'formatter': 'errors',
#         },
#     'security': {
#             'level': 'INFO',
#             'class': 'logging.FileHandler',
#             'filename': 'logs/security.log',
#             'formatter': 'security'
#         },
#     'mail_admins': {
#             'level': 'ERROR',
#             'filters': ['require_debug_false', ],
#             'class': 'django.utils.log.AdminEmailHandler',
#             'formatter': 'mail'
#         },
#     },
# 'loggers': {
#         'django': {
#             'handlers': ['console', 'console_warning', 'console_error', 'general'],
#             'propagate': True,
#         },
#         'django.request': {
#             'handlers': ['mail_admins'],
#             'level': 'ERROR',
#             'propagate' : False,
#         },
#         'django.server': {
#             'handlers': ['errors', 'mail_admins', ],
#             'propagate': True,
#         },
#         'django.template': {
#             'handlers': ['errors'],
#             'propagate': True,
#         },
#         'django.db.backends': {
#             'handlers': ['errors'],
#             'propagate': True
#         },
#         'django.security': {
#             'handlers': ['security'],
#             'propagate': False,
#         }
#     }
# }